### ISSUE TITLE
楼主研究一下导出pdf功能？

### ISSUE THREAD

**Issue by Gowa2017** [ystcode/JustWrite#11]
typora 导出 pdf 的效果很棒，但是其迟迟不加入对于一些功能的支持，

无法。

**Comment by yueshutong** [comment]
暂时只支持导出HTML文件，导出PDF可以借助浏览器的打印功能。

**Comment by Gowa2017** [comment]
@yueshutong 加入对于 vizjs  mermaid 的支持吧 这样就更加给力了

**Comment by ystcode** [comment]
好
